Stack
cogentcore/yaegi pull request #1
Opened 2024-11-27 04:12 UTC by breadchris

2025-07-14 16:30 UTC, kkoreilly requested changes
Thanks for filing this. Please see my comment.

2025-07-14 16:30 UTC, kkoreilly commented on _test/c2/c2.go
> +import "github.com/traefik/yaegi/_test/c1"
The diff is cluttered because of a change in the URL. If you could find-and-replace github.com/traefik/yaegi with github.com/cogentcore/yaegi, that would be great!

2025-07-15 04:55 UTC, breadchris commented
I didn't mean to file this PR, must have been a miss click in github. I love the work that y'all are doing with this project, and I would love to have your changes merged into traefik's repo!

2025-07-15 04:55 UTC, closed without merging

2025-07-15 16:36 UTC, kkoreilly commented
@breadchris Thanks for the reply! I suspected that might be the case.